services:
  eleven-server:
    image: 831926627674.dkr.ecr.ap-northeast-2.amazonaws.com/eleven-server
    ports:
      - 8080:8080
    restart: always
    depends_on:
      eleven-db:
        condition: service_healthy

  eleven-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_DATABASE: elevendb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10