services:
  eleven-server:
    image: 831926627674.dkr.ecr.ap-northeast-2.amazonaws.com/eleven-server
    container_name: mvp_back-eleven-server-1
    platform: linux/amd64
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      eleven-db:
        condition: service_healthy

  eleven-db:
    container_name: mvp_back-eleven-db-1
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: eleven_prod
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
