spring:
  application:
    name: MVP_back

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY_ID}
        secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: eleven-static-files

jwt:
  secret: ${JWT_SECRET}